token: "123456:xxxxxxx"  # Telegram token for the bot
password: "bot_password"  # A password to authenticate new users

# Root directory for downloads (should be configured for transmission manually)
# Currently used only to check free space
rootdir: "/mnt/data/transmission_downloads"
# Minimal amount of free space (in bytes) on the partition with rootdir.
# If the amount of free space goes below this number, all torrents are automatically stopped.
# Use 0 to disable free space checker
reserved_space: 1000000000  # ~1 GB

client_cfg:  # Options for transmission-rpc client
    host: "127.0.0.1"
    port: 9091
    username: "transmission"
    password: "some_secure_password"

ftp:
    enabled: False  # If disabled, all other options are ignored
    address: "192.168.1.10:2100"  # address and port to listen on
    # Time limit in seconds. After this period opened FTP shares will be automatically closed
    tl: 3600
